// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkxviwzykdfdcgqydymz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFreHZpd3p5a2RmZGNncXlkeW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzQxODgsImV4cCI6MjA2NTQ1MDE4OH0.qrFeN3f2vNMioTlWGge4e8NUQKMisYTKPycGKmqjv3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);